//[146] 
//[146.1] ESTADO CONSULTAR TODOS LOS PRODUCTOS
export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST"  

//[146.2] ESTADO CONFIRMACIÓN AL VER TODOS LOS PRODUCTOS
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"

//[146.3] ESTADO DONDE ME DICE QUE FALLE AL INTENTAR VER PRODUCTOS
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"           


//[147]
//[147.1] ESTADO PARA LIMPIAR POSIBLES ERRORES
export const CLEAR_ERRORS="CLEAR_ERRORS"